<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>GarageKept.OutlookAlarm.Alarm.Program</StartupObject>
    <Version>2.2.0</Version>
    <AssemblyVersion>2.2.0.0</AssemblyVersion>
    <FileVersion>2.2.0.0</FileVersion>
    <ApplicationIcon>Clock.ico</ApplicationIcon>
    <AssemblyName>GarageKept.OutlookAlarm.O365</AssemblyName>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Helpers\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Audio\Media\double-beep.wav" />
    <None Remove="Audio\Media\guitar-notification.wav" />
    <None Remove="Audio\Media\tick-tock.wav" />
    <None Remove="Audio\Media\urgent-simple-tone.wav" />
  </ItemGroup>


  <ItemGroup>
    <Content Include="Clock.ico" />
    <Content Include="alarmClock.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.87.0" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.87.0" />
    <PackageReference Include="NAudio" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Audio\Media\double-beep.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Audio\Media\guitar-notification.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Audio\Media\tick-tock.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Audio\Media\urgent-simple-tone.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="UI\Controls\AlarmControl.cs" />
    <Compile Update="UI\Controls\AlarmProgressBar.cs" />
    <Compile Update="UI\Controls\AlarmContainerControl.cs" />
    <Compile Update="UI\Forms\AlarmForm.cs" />
    <Compile Update="UI\Forms\BaseForm.cs" />
    <Compile Update="UI\Forms\MainForm.cs" />
    <Compile Update="UI\Forms\SettingsForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="UI\Controls\AlarmControl.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
